### ISSUE TITLE
Unable to delete file: /data/lost+found, openfdat /data/lost+found: permission denied

### ISSUE THREAD

**Issue by jdambly-ns** [kubevirt/containerized-data-importer#2685] opened 2023-04-07 19:59 UTC
**What happened**:
creating a virutal machine with a dataVolume results in the import pod crashing with the following logs
```
(⎈ |cfw-test-nc4:vms)➜  ~ kubectl logs importer-haproxy01
I0407 19:41:11.660407       1 importer.go:103] Starting importer
I0407 19:41:11.660460       1 importer.go:168] begin import process
I0407 19:41:11.661358       1 registry-datasource.go:172] Copying proxy certs
I0407 19:41:11.661537       1 registry-datasource.go:57] Error creating allCertDir open /proxycerts/: no such file or directory
I0407 19:41:11.661744       1 data-processor.go:379] Calculating available size
I0407 19:41:11.661870       1 data-processor.go:391] Checking out file system volume size.
I0407 19:41:11.661994       1 data-processor.go:399] Request image size not empty.
I0407 19:41:11.662120       1 data-processor.go:404] Target size 23054442496.
I0407 19:41:11.662329       1 util.go:38] deleting file: /data/lost+found
E0407 19:41:11.662509       1 util.go:41] Unable to delete file: /data/lost+found, openfdat /data/lost+found: permission denied
E0407 19:41:11.662768       1 importer.go:177] openfdat /data/lost+found: permission denied
Failure cleaning up target space
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:181
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
```

**What you expected to happen**:
importer to import the docker image I'm using for my vm image, and the vm to start properly

**How to reproduce it (as minimally and precisely as possible)**:
deploy the following virtualmachine

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    meta.helm.sh/release-name: virtual-machines
    meta.helm.sh/release-namespace: vms
  creationTimestamp: "2023-04-07T01:59:45Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: virtual-machines
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dp-lab
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: dp-lab-0.1.0
    kubevirt.io/domain: haproxy01
  name: haproxy01
  namespace: vms
  resourceVersion: "1961106"
  uid: c8fd3bfa-779e-4478-8efa-f1f61880922d
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: virtual-machines
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: dp-lab
        app.kubernetes.io/version: 0.0.1
        helm.sh/chart: dp-lab-0.1.0
        kubevirt.io/domain: haproxy01
      name: haproxy01
      namespace: vms
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 22Gi
      source:
        registry:
          url: docker://<## REDACTED ##>/ns-ubuntu-20-04-qemu:v0.0.1
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: virtual-machines
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: dp-lab
        app.kubernetes.io/version: 0.0.1
        helm.sh/chart: dp-lab-0.1.0
        kubevirt.io/domain: haproxy01
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: imagedisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - macAddress: 52:54:00:e6:1f:81
            masquerade: {}
            name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "2"
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: haproxy01
        name: imagedisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            run-cmd:
              - ["salt-call", "state.apply", "salt.bootstrap", "--master=" ]
              - ["salt-call", "state.apply", "salt.minion", "--master="]
              - ["apt-get", "install", "-y", "haproxy"]
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: "2023-04-07T01:59:45Z"
    lastTransitionTime: "2023-04-07T01:59:45Z"
    message: VMI does not exist
    reason: VMINotExists
    status: "False"
    type: Ready
  printableStatus: DataVolumeError
  volumeSnapshotStatuses:
  - enabled: false
    name: imagedisk
    reason: 'No VolumeSnapshotClass: Volume snapshots are not configured for this
      StorageClass [csi-cinder-sc-retain] [imagedisk]'
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
```

docker image file
```
FROM scratch
ADD --chown=107:107 ns-ubuntu-20-04-qemu /disk/
```

**Additional context**:
I think the issue is that the import pods are no longer run as root, but the dir `/data/lost+found` does this really need to be deleted?

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.56.0
- Kubernetes version (use `kubectl version`): v1.24.10
- DV specification: N/A
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
  creationTimestamp: "2023-04-07T01:59:45Z"
  generation: 339
  labels:
    app.kubernetes.io/instance: virtual-machines
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dp-lab
    app.kubernetes.io/version: 0.0.1
    app.netskope.io/name: haproxy
    helm.sh/chart: dp-lab-0.1.0
    kubevirt.io/created-by: c8fd3bfa-779e-4478-8efa-f1f61880922d
    kubevirt.io/domain: haproxy01
    netskope.io/vm: "true"
  name: haproxy01
  namespace: vms
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: haproxy01
    uid: c8fd3bfa-779e-4478-8efa-f1f61880922d
  resourceVersion: "1977253"
  uid: 68ef575c-dffa-46d3-b6c4-88bc13f387b9
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 22Gi
  source:
    registry:
      url: docker://artifactory.netskope.io/pe-docker/ns-ubuntu-20-04-qemu:v0.0.1
status:
  claimName: haproxy01
  conditions:
  - lastHeartbeatTime: "2023-04-07T01:59:48Z"
    lastTransitionTime: "2023-04-07T01:59:48Z"
    message: PVC haproxy01 Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-04-07T19:56:34Z"
    lastTransitionTime: "2023-04-07T01:59:45Z"
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-04-07T19:56:34Z"
    lastTransitionTime: "2023-04-07T19:56:34Z"
    message: 'Unable to process data: Failure cleaning up target space: openfdat /data/lost+found:
      permission denied'
    reason: Error
    status: "False"
    type: Running
  phase: ImportInProgress
  progress: N/A
  restartCount: 194
```
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): Linux knode01 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment] 2023-04-10 08:08
Hi @jdambly-ns, thanks for opening this issue.

It looks like this bug has just been fixed in https://github.com/kubevirt/containerized-data-importer/pull/2676 (we were trying to delete some files that weren't explicitly created by CDI).

A version bundled with this fix should be ready soon. Let us know if it solves your problem!

**Comment by xuzhenglun** [comment] 2023-04-10 13:15
if setting accessModes of PVC to `ReadWriteMany`,  write permission would occur too.

<details>
<summary>Here is importer log</summary>

```
I0410 13:01:16.409931       1 importer.go:103] Starting importer
I0410 13:01:16.409983       1 importer.go:168] begin import process
I0410 13:01:16.411819       1 data-processor.go:356] Calculating available size
I0410 13:01:16.411842       1 data-processor.go:368] Checking out file system volume size.
I0410 13:01:16.411857       1 data-processor.go:376] Request image size not empty.
I0410 13:01:16.411874       1 data-processor.go:381] Target size 41940099072.
I0410 13:01:16.412264       1 nbdkit.go:302] Waiting for nbdkit PID.
I0410 13:01:16.913100       1 nbdkit.go:323] nbdkit ready.
I0410 13:01:16.913123       1 data-processor.go:255] New phase: Convert
I0410 13:01:16.913138       1 data-processor.go:261] Validating image
I0410 13:01:16.921722       1 qemu.go:332] Adding preallocation method: [-o preallocation=falloc]
I0410 13:01:16.926058       1 qemu.go:258] 0.00
E0410 13:01:16.929767       1 prlimit.go:174] qemu-img failed output is:
E0410 13:01:16.929789       1 prlimit.go:175]     (0.00/100%)

E0410 13:01:16.929796       1 prlimit.go:176] qemu-img: /data/disk.img: error while converting raw: Could not create '/data/disk.img': Permission denied

E0410 13:01:16.929884       1 data-processor.go:251] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
	pkg/system/prlimit.go:178
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:111
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw.func1
	pkg/image/qemu.go:123
kubevirt.io/containerized-data-importer/pkg/image.addPreallocation
	pkg/image/qemu.go:338
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:122
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:145
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:280
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
could not convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:135
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:145
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:280
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:282
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:215
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
E0410 13:01:16.930029       1 importer.go:177] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
	pkg/system/prlimit.go:178
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
	pkg/system/prlimit.go:111
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw.func1
	pkg/image/qemu.go:123
kubevirt.io/containerized-data-importer/pkg/image.addPreallocation
	pkg/image/qemu.go:338
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:122
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:145
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:280
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
could not convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
	pkg/image/qemu.go:135
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
	pkg/image/qemu.go:145
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:280
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
	pkg/importer/data-processor.go:282
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
	pkg/importer/data-processor.go:215
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:248
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:157
main.handleImport
	cmd/cdi-importer/importer.go:174
main.main
	cmd/cdi-importer/importer.go:140
runtime.main
	GOROOT/src/runtime/proc.go:250
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
```

</details>



I just dig this problem for some time, I realize that since `ReadWriteMany` CSI PV would skip SetVolumeOwnership, and `fsGroup` would not work. 

BTW: I tested this in Kubernetes 1.20, which is an old version. But the behavior in the latest code seems the same. see more: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L332

**Comment by xuzhenglun** [comment] 2023-04-10 13:53
I occurred this issue too. After some digging, I realize that the root cause of the `permission deny` error can be the CSIDriver configuration.

`CSIDriver.spec.fsGroupPolicy` default set to `ReadWriteOnceWithFSType`, and It will skip setting fsGroup Permission of Volime. after changing it to `File`, the problem is solved.

**Comment by alromeros** [comment] 2023-05-03 08:37
Hello @jdambly-ns, just wanted to let you know that the fix for this behavior is already included in [v1.54.2](https://github.com/kubevirt/containerized-data-importer/releases/tag/v1.54.2). Hope that helps! Feel free to close the issue if everything is good.

**Comment by Learntotolearn** [comment] 2023-06-10 06:38
I also encountered the same problem. My version of v.1.56.0

**Comment by akalenyu** [comment] 2023-06-19 12:25
> I also encountered the same problem. My version of v.1.56.0

@awels, can we make a 1.56.z release containing the fix for this? (https://github.com/kubevirt/containerized-data-importer/pull/2676)

**Comment by alromeros** [comment] 2023-07-31 11:46
@awels we also need to include https://github.com/kubevirt/containerized-data-importer/pull/2646 (according to https://github.com/kubevirt/containerized-data-importer/pull/2825). It would be a good opportunity to do the release so we include the two fixes.

**Comment by awels** [comment] 2023-07-31 13:49
1.56.1 was just released, which should include these fixes.

**Comment by alromeros** [comment] 2023-07-31 14:08
That's great, thanks @awels! I think it's safe to close this issue then.

**Comment by alromeros** [comment] 2023-08-02 15:27
With the backport released I think it's safe to close this issue. Feel free to reopen if necessary, thanks!

**Closed by alromeros** 2023-08-02 15:27 UTC
Labels: kind/bug

**Comment by yuan2go** [comment] 2023-08-31 01:59
I also encountered the same problem. I upgraded the version to 1.56.1 and still have the same problem
