### ISSUE TITLE
cdi operator uses cluster-admin ClusterRole. 

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/containerized-data-importer#759] opened 2019-04-22 21:48 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

The cdi operator's service account is bound to the 'cluster-admin' ClusterRole, which i believe grants more permissions than the operator needs. 

This issue is a request to limit the scope of the permissions given to the cdi-operator to only what is required to manage the deployment/updating/deprovisioning of the cdi infrastructure.

**Comment by mhenriks** [comment] 2019-04-23 13:39
Oh yeah, this is bad but should be fixed in #748

**Comment by mhenriks** [comment] 2019-05-03 18:44
No longer uses cluster-admin but permissions are still too broad.  Currently all Operator permissions exist in a single ClusterRole.  But some of those permissions only need apply to the namespace CDI is installed in.

**Comment by annastopel** [comment] 2019-05-14 11:12
The issue is resolved in  #748

**Closed by annastopel** 2019-05-14 11:12 UTC
