### ISSUE TITLE
Datavolume resource was disappeared. 

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/containerized-data-importer#2510] opened 2022-12-16 02:58 UTC
**What happened**:
After upgrade Kubevirt and CDI to v0.58.0 and v1.55.1, some VM creating flow is changed.
To create VM with DatavolumeTemplates, dv resource is disappeared and I found the only pvc resource.

Before upgrade, dv resouce is always along with pvc resource. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): N/A
- Kubernetes version (use `kubectl version`): N/A
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment] 2022-12-16 04:52
Yes, we are garbage collecting DVs once they complete with 1.55. This is completely normal behavior. DataVolumes serve no purpose anymore after they complete as they are essentially a mechanism for populating a PVC. The PVC is the thing actually used by the Virtual Machine.

**Comment by qkfrksvl** [comment] 2022-12-16 07:23
Thanks to awels :) 
One question, Is there another way to extend VM Disk size other than increasing the pvc size statically ?

**Comment by awels** [comment] 2022-12-16 13:25
Increasing the PVC size is the only way. On the next restart it will automatically resize the disk image. You are still responsible for changing the guest OS partition with the new size (or creating a new partition depending on your needs)

**Comment by mhenriks** [comment] 2022-12-19 12:48
> Increasing the PVC size is the only way. On the next restart it will automatically resize the disk image. You are still responsible for changing the guest OS partition with the new size (or creating a new partition depending on your needs)

restart should not be required

**Comment by alromeros** [comment] 2023-03-08 11:22
Since everything got cleared and this is not a bug, can we close the issue @qkfrksvl  @awels @mhenriks? Thanks!

**Comment by aglitke** [comment] 2023-03-27 12:34
Closing per the previous comment.

**Closed by aglitke** 2023-03-27 12:34 UTC
Labels: kind/bug
