### ISSUE TITLE
CDI download fails due to nbdkit: curl error

### ISSUE THREAD

**Issue by k8scoder192** [kubevirt/containerized-data-importer#2561] opened 2023-01-27 20:50 UTC
**What happened**:
**CDI download of large image file (380M) fails with error**
```I0127 02:55:25.226441       1 nbdkit.go:290] Log line from nbdkit: nbdkit: curl[4]: error: pread: curl_easy_perform: Failed sending data to the peer: Connection died, tried 5 times before giving up
E0127 02:55:26.347182       1 prlimit.go:174] qemu-img failed output is:
E0127 02:55:26.347210       1 prlimit.go:175]     (0.00/100%)
    (1.02/100%)
    (2.09/100%)
    (3.16/100%)
    (4.22/100%)
    (5.22/100%)
    (6.26/100%)
    (7.32/100%)
    (8.33/100%)
    (9.33/100%)
    (10.39/100%)
    (11.39/100%)
    (12.39/100%)
    (13.39/100%)
    (14.40/100%)
    (15.40/100%)


E0127 02:55:26.347218       1 prlimit.go:176] qemu-img: error while reading at byte 379387904: Input/output error
```
**Describe on importer pod output**
```    Last State:     Terminated
      Reason:       Error
      Message:      Unable to process data: Unable to convert source data to target format: Conversion to Raw failed: could not convert image to raw Log line from nbdkit: nbdkit: curl[4]: error: pread: curl_easy_perform: Failed sending data to the peer: Connection died, tried 5
times before giving up: qemu-img execution failed: exit status 1
      Exit Code:    1
      Started:      Fri, 27 Jan 2023 15:40:40 -0500
      Finished:     Fri, 27 Jan 2023 15:45:06 -0500
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     4
      memory:  10Gi
    Requests:
      cpu:     1
      memory:  8Gi
    Environment:
      IMPORTER_SOURCE:               http
      IMPORTER_ENDPOINT:             https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
      IMPORTER_CONTENTTYPE:          kubevirt
      IMPORTER_IMAGE_SIZE:           10Gi
      OWNER_UID:                     ffccd373-9db1-4712-9d4a-4ab7ff23e006
      FILESYSTEM_OVERHEAD:           0
      INSECURE_TLS:                  false
      IMPORTER_DISK_ID:
      IMPORTER_UUID:
      IMPORTER_READY_FILE:
      IMPORTER_DONE_FILE:
      IMPORTER_BACKING_FILE:
      IMPORTER_THUMBPRINT:
      http_proxy:
      https_proxy:
      no_proxy:
      IMPORTER_CURRENT_CHECKPOINT:
      IMPORTER_PREVIOUS_CHECKPOINT:
      IMPORTER_FINAL_CHECKPOINT:
      PREALLOCATION:                 false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wwxgd (ro)
    Devices:
      /dev/cdi-block-volume from cdi-data-vol
```

**What you expected to happen**:
CDI should be able to download and convert image file to raw without connection issues.

wget of source `https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img` works flawlessly even when ran multiple times.

**How to reproduce it (as minimally and precisely as possible)**:
Ceph block storage (PVC in block mode)
CDI v1.54.0

```---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu1804-dv
spec:
  source:
    http:
      url: "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
  pvc:
    storageClassName: rook-ceph-block
    volumeMode: Block
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
```
Also cdi CR resources were increased to eliminate this as a possible issue 
```   config:
        podResourceRequirements:
          limits:
            cpu: "4"
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 8Gi
 ``` 
**Additional context**:
It appears using nbdkit to curl the file could be causing issues. 

Support for this stems from the fact that when using CDI to download `.xz` files, nbdkit is **not** used and **no** connection issues were seen (even when ran multiple times). 

In the `.xz` case, a golang http client downloads to scratch space and when complete, qemu-img starts the conversion to a raw. See [PR 2351](https://github.com/kubevirt/containerized-data-importer/pull/2351) 

**Others have seen nbdkit curl errors** 
See [issue 1737](https://github.com/kubevirt/containerized-data-importer/issues/1737) and see step 5 (log output) in [issue 1980](https://github.com/kubevirt/containerized-data-importer/issues/1980) 

Suggestion: Don't use nbdkit to curl, use same method as code currently uses for `.xz` files

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.54.0
- Kubernetes version (use `kubectl version`): v1.24.0 and/or v1.21.0
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15
- Install tools: N/A
- Others: ceph:v16.2.7, rook/ceph:v1.9.2

**Comment by rwmjones** [comment] 2023-01-30 13:23
Have a look at:
https://libguestfs.org/nbdkit-retry-filter.1.html
https://libguestfs.org/nbdkit-retry-request-filter.1.html
https://libguestfs.org/nbdkit-readahead-filter.1.html
https://libguestfs.org/nbdkit-cache-filter.1.html

Adding these filters allows nbdkit to read ahead and recover from short network failures.

**Comment by rwmjones** [comment] 2023-01-30 13:45
This is how we arrange the filters in virt-v2v, on top of nbdkit-curl-plugin:
```
nbdkit --filter=cache --filter=cacheextents --filter=retry curl \
    cache-on-read=true \
    cache-max-size=1G
```

A few notes about this:

 * `cache-on-read=true` is important, so that reads are actually cached (otherwise only the special NBD prefetch operation is cached).
 * The cacheextents filter is needed because of the way that qemu-img makes inefficient requests for extent data.
 * I've suggested `cache-max-size=1G` to limit the cache to 1G, but of course you may wish to adjust this.  Note by default the cache will use all available `/var/tmp` unless you limit it.
 * We were using the readahead filter and then dropped it.  However in the meantime I rewrote this filter upstream (nbdkit >= 1.31.2).  If you know that you're using the newer nbdkit then you might consider adding `--filter=readahead` first in the list, but we don't have much experience yet of whether it's really going to solve the problem.

Do you have an example of a source where the current nbdkit command is especially slow?

**Comment by mhenriks** [comment] 2023-01-31 20:41
@rwmjones here is a nice slow url from #2358

https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img

**Comment by rwmjones** [comment] 2023-01-31 20:53
Thanks - I'll play with it tomorrow & see if I can reproduce it and come up with suggestions.

**Comment by mhenriks** [comment] 2023-02-01 18:18
@rwmjones thanks for digging into this!  Good to know the retry filter will address the issue here.

I think it would be best to track your performance related work/observations in #2358 in which we would like to see if qemu-img + nbdkit can perform as well as wget to scratch space then qemu-img convert locally

**Comment by alromeros** [comment] 2023-03-16 17:04
Since https://github.com/kubevirt/containerized-data-importer/pull/2584 is merged, @k8scoder192 have you been able to replicate your issue again with the retry filter? If the download failure has been addressed I think we can consider closing the issue, unless we want to continue with the performance conversation here.

**Comment by k8scoder192** [comment] 2023-03-23 15:09
@alromeros I can't test this unless the fix is backported to CDI v1.54. Can someone do that? 1.55 introduced issues (pod doesn't run as root, which fails with my current cluster config)

**Comment by alromeros** [comment] 2023-03-23 18:20
> @alromeros I can't test this unless the fix is backported to CDI v1.54. Can someone do that? 1.55 introduced issues (pod doesn't run as root, which fails with my current cluster config)

@k8scoder192 sure, we can backport the fix to that version. I'll let you know once we release the version with the fix.

**Comment by aglitke** [comment] 2023-03-27 12:50
Backport PR is #2666

**Comment by k8scoder192** [comment] 2023-03-31 18:14
@awels @aglitke @mhenriks 
v1.54.1 seems to work, so I'd say the issue appears to to be resolved.

**Comment by awels** [comment] 2023-03-31 18:24
Excellent, feel free to close the issue then.

**Closed** 2023-03-31 22:17 UTC
Labels: kind/bug
