### ISSUE TITLE
Virtual image size is larger than the reported available storage

### ISSUE THREAD

**Issue by g7nguym** [kubevirt/containerized-data-importer#3159] opened 2024-04-01 10:44 UTC
**What happened**:
I tried to upload .iso image via CDI to a PVC. The iso image is nearly 5GB. It always throws an error saying the virtual image is larger than the reported available storage. I have tried multiple PVC sizes: 12Gi, 64Gi, 120Gi but it is not working.

**What you expected to happen**:
The iso image should be successfully uploaded to PVC

**How to reproduce it (as minimally and precisely as possible)**:
Following command: 
kubectl virt image-upload pvc win-2022-std-iso --size=120Gi --image-path=win22-std.iso --storage-class=datavg-thin-pool --uploadproxy-url=https://10.49.172.185:31876 --insecure --wait-secs=60 --access-mode=ReadWriteOnce --force-bind
PVC default/win-2022-std-iso not found
PersistentVolumeClaim default/win-2022-std-iso created
Waiting for PVC win-2022-std-iso upload pod to be ready...
Pod now ready
Uploading data to https://10.49.172.185:31876

 4.67 GiB / 4.67 GiB [==========================================================================================================================================================] 100.00% 2m13s

unexpected return value 400, Saving stream failed: Virtual image size 12886302720 is larger than the reported available storage 12884901888. A larger PVC is required.

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.58.3
- Kubernetes version (use `kubectl version`): 1.29.0
- DV specification: N/A
- Cloud provider or hardware configuration: kind
- OS (e.g. from /etc/os-release): Rocky Linux 9.3
- Kernel (e.g. `uname -a`): 5.14.0-362.24.1.el9_3.x86_64
- Install tools: kubectl virt
- Others: N/A

**Comment by akalenyu** [comment] 2024-04-01 11:14
Definitely weird - the error indicates that only 12Gi is available in the volume (even though you asked for 120)
Is it possible that the storage provisioner (`--storage-class=datavg-thin-pool`) is providing a volume smaller than the request?

You could test this by creating a 120Gi PVC and a pod mounting it;
Then run something like (%a - available (what we care about), %f - total free)
```bash
bash-5.1# stat /pvcmountpath/ -fc %a
907
bash-5.1# stat /pvcmountpath/ -fc %f
974
```
To get total size you would multiply by the block size (`stat /pvcmountpath/ -fc %s`)

**Comment by g7nguym** [comment] 2024-04-01 11:38
Hi @akalenyu 
Thanks for taking time looking into my issue.
I have tested by creating a PVC of 128Gi
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          VOLUMEATTRIBUTESCLASS   AGE
slmitswinp1-pvc    Bound    pvc-36655653-b079-4872-b20f-e64bf8a5ae50   128Gi      RWX            datavg-thin-pool      <unset>                 26m
I then mounted it into a pod:
[root@k8s-master-01 ~]# kubectl exec pods/nginx -- stat /var/www/html/ -fc %s
4096
[root@k8s-master-01 ~]# kubectl exec pods/nginx -- stat /var/www/html/ -fc %a
31068944
[root@k8s-master-01 ~]# kubectl exec pods/nginx -- stat /var/www/html/ -fc %f
32750812

It looks like the size of my pvc is only 4096 bytes?

**Comment by akalenyu** [comment] 2024-04-01 11:51
Actually, the size of your PVC is around 120Gi - `31068944 * 4096` (available blocks * block size)
It is definitely weird that a disk.img is already existing there, unless you tried the upload before creating the nginx pod

**Comment by alromeros** [comment] 2024-04-01 13:34
Maybe this case is similar to the one described here https://issues.redhat.com/browse/CNV-36769? If a first upload attempt failed for some unrelated reason (maybe the upload pod was force-deleted), then in subsequent retries the original img.disk will be there occupying space and preventing the upload from succeeding, as @akalenyu suggested.

**Comment by akalenyu** [comment] 2024-04-01 14:17
> I made some progress with this issue by using --volume-mode=FileSystem. This option works. If the PVC is block volume, it doesn't work. I don't really have an explaination for this. Even if I delete the block PVC completely and create a new one, it always shows larger size PVC needed message.

ah okay if this is block, you could repeat the nginx experiment but instead use `blockdev --getsize64 /dev/pvcdevicepath`

**Comment by awels** [comment] 2024-04-01 14:21
So I am wondering, which version of virtctl plugin do you have. I see you are creating a `PVC` with `kubectl virt image-upload pvc win-2022-std-iso --size=120Gi --image-path=win22-std.iso --storage-class=datavg-thin-pool --uploadproxy-url=https://10.49.172.185:31876/ --insecure --wait-secs=60 --access-mode=ReadWriteOnce --force-bind` instead of a `dv` which should generate a message about not using datavolumes IIRC, and I don't see that

**Comment by awels** [comment] 2024-04-01 14:33
Interesting can you try Alex's suggestion of using `blockdev` to see the size of the device properly, in both the smaller case and larger case, maybe there is some overhead we are not aware of?

**Comment by g7nguym** [comment] 2024-04-01 14:41
Interestingly enough. Now it works with windows iso as well which didn't work before. I can not reproduce the issue now unfortunately.
The storage backend I am using is Linstor.
kubectl virt image-upload pvc nginx-test-iso --size=64Gi --image-path=/root/win22-std.iso --storage-class=datavg-thin-pool --uploadproxy-url=https://10.248.83.131:443 --insecure --wait-secs=60 --access-mode=ReadWriteOnce --force-bind
PVC default/nginx-test-iso not found
PersistentVolumeClaim default/nginx-test-iso created
Waiting for PVC nginx-test-iso upload pod to be ready...
Pod now ready
Uploading data to https://10.248.83.131:443

 4.67 GiB / 4.67 GiB [==========================================================================================================================================================] 100.00% 2m11s

Uploading data completed successfully, waiting for processing to complete, you can hit ctrl-c without interrupting the progress
Processing completed successfully
Uploading /root/win22-std.iso completed successfully

**Comment by akalenyu** [comment] 2024-04-01 15:10
Hmm maybe sometimes the linstor csi driver messes up the size calc? iirc you were doing `--size=120Gi` before, now you're using 64

**Comment by g7nguym** [comment] 2024-04-01 22:36
I've been trying multiple sizes before, 40Gi, 64Gi, 120Gi. None of it worked. I will try out Portworx at a later time to see if it is more stable.
Thank you for all of your help in this issue.

**Comment by aglitke** [comment] 2024-04-08 12:05
@kvaps Do you have any insight as to what might be happening with LinStore here?

**Comment by akalenyu** [comment] 2024-07-15 12:25
> I've been trying multiple sizes before, 40Gi, 64Gi, 120Gi. None of it worked. I will try out Portworx at a later time to see if it is more stable. Thank you for all of your help in this issue.

Hey, did you get a chance to try this with a different provisioner?

**Comment by kvaps** [comment] 2024-10-10 15:15
/reopen 

The issue still persists

```
virtctl image-upload dv win10-iso --size=8Gi --image-path ~/Downloads/Win10_21H2_EnglishInternational_x64.iso --storage-class=replicated --uploadproxy-url=https://localhost:8443 --insecure
PVC tenant-kvaps/win10-iso not found
DataVolume tenant-kvaps/win10-iso created
Waiting for PVC win10-iso upload pod to be ready...
Pod now ready
Uploading data to https://localhost:8443

 5.48 GiB / 5.48 GiB [=========================================================================================================================================================] 100.00% 8m56s

You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v1.1.0
Server Version: v1.3.1
unexpected return value 400, Saving stream failed: virtual image size 8589942784 is larger than the reported available storage 8589934592. A larger PVC is required
```

**Comment by kvaps** [comment] 2024-10-10 15:27
```
root@srv2:/# lsblk -bno SIZE /dev/drbd1014
1073750016
```

**Comment by kvaps** [comment] 2024-10-11 09:21
@aglitke any Idea where this reported VirtualSize of `1073741824` comes from?

**Comment by kvaps** [comment] 2024-10-11 09:34
I just reported this issue to LINSTOR: https://github.com/LINBIT/linstor-server/issues/421

But does this check really makes sense? When I create a new volume I expect that it will be larger anyway.

**Comment by kvaps** [comment] 2024-10-11 10:20
Maybe should we add `blockOverhead` option, that works the same way as `filesystemOverhead` but for block devices?

**Comment by awels** [comment] 2024-10-11 12:44
The main reason we have the fsOverhead is because filesystems themselves take up space on the block device. For a block device we don't have this overhead. The way we get the available space on block device size is `/usr/sbin/blockdev --getsize64 <device path>` The function is here https://github.com/kubevirt/containerized-data-importer/blob/main/pkg/util/file.go#L121-L142 and then we compare that to the information we got from qemu-img.

**Comment by kvaps** [comment] 2024-10-11 17:26
In my case blockdev reports the same size as qemu-img:

```
/ # qemu-img info /dev/drbd1000
image: /dev/drbd1000
file format: raw
virtual size: 1 GiB (1073750016 bytes)
disk size: 0 B
Child node '/file':
    filename: /dev/drbd1000
    protocol type: host_device
    file length: 1 GiB (1073750016 bytes)
    disk size: 0 B
```

```
/ # blockdev --getsize64 /dev/drbd1000
1073750016
```

And this size is larger than `1Gi` requested in PVC

**Comment by kvaps** [comment] 2024-10-11 17:35
It's up to consideration https://github.com/kubevirt/containerized-data-importer/pull/3458

**Comment by kvaps** [comment] 2024-10-12 13:57
@awels LINSTOR creates block device a bit larger size than requested in PVC. I think this is an issue for CDI.

If I understand this correctly there is no easy way for preparing a volume with exactly requested size using LINSTOR and DRBD.

@ghernadi please correct me if I'm wrong about this ^^

So for now I don't understand on which side this issue should be fixed? CDI or LINSTOR?

From the messages above Portworks have the same issue.

**Comment by phoracek** [comment] 2024-10-13 23:08
Hello. I'm getting the same issue on K3s with rancher.io/local-path provisioner.

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "ha-dv"
spec:
  source:
      http:
         url: "https://github.com/home-assistant/operating-system/releases/download/13.1/haos_ova-13.1.qcow2.xz"
  storage:
    volumeMode: Filesystem
    resources:
      requests:
        storage: "31G"
```

No matter how much I increase the requested storage, the import always fails with "irtual image size 34359738368 is larger than the reported available storage 32804339539. A larger PVC is required".

**Comment by ghernadi** [comment] 2024-10-14 06:50
> @awels LINSTOR creates block device a bit larger size than requested in PVC. I think this is an issue for CDI.
> 
> If I understand this correctly there is no easy way for preparing a volume with exactly requested size using LINSTOR and DRBD.
> 
> @ghernadi please correct me if I'm wrong about this statement ^^
> 
> So for now I don't understand on which side this issue should be fixed? CDI or LINSTOR?

This reminds me of a similar issue we had with our Proxmox plugin, where Proxmox also wants the exact same size when moving an existing Proxmox volume into a DRBD resource.
For this reason LINSTOR introduced the property `DrbdOptions/ExactSize`. When this property is set to `True` (default is `False`), DRBD's `.res` file gets the `size ${size};` property set, which causes the resulting DRBD device to be exactly as large as the user requested (i.e. LINSTOR's volume-definition size) even if the backing device is a bit larger (due to rounding up to the next extent size for example).

Feel free to use this property for such migrations  volumes, but please make sure to **DELETE THIS PROPERTY** once the migration is finished.   
It is **not recommended to have this property active during production** . This property is only meant to be set during the migration.

We had already tried in the past to automatically manage DRBD's `size` property, but we always run into issues. There are quite some scenarios that are more complicated internally than one would think, making the usage of DRBD's `size` property quite tricky (especially during resize events, (partially) failing resizes, etc... ). 

-------------

Alternative solution: Tell LINSTOR to configure DRBD with external metadata. This can of course also stay in production.

This alternative solution works simply because if the user requests a 1GB volume, LINSTOR will create 2 devices. Assuming LVM with default settings as a backing storage, one of the devices will have exactly 1 GB (which will also be reported by DRBD and LINSTOR as "usable size"), and a 4MB device, from which DRBD only uses a few KiB for its own metadata. So the "a bit more space" (i.e. the unused 3.something MiB) is now "trapped" in the external metadata device and therefore cannot be part of the usable space.

**Comment by kvaps** [comment] 2024-10-14 15:39
@ghernadi many thanks for such detailed comment and sharing your experience 🙏 

It's very interesting to learn about this opportunity. But I think we can't teach CDI for adding DRBD specific options as it works purely with Kubernetes PVCs.

Besides, I am sure that this issue also affects other storage providers that base their logic on LVM and ZFS (eg. [topolvm](https://github.com/topolvm/topolvm) and [democratic-csi](https://github.com/democratic-csi/democratic-csi))

I am proposing a fix to CDI that takes into account both the requested size and the actual size of the block device and takes the larger one. Here is a PR: https://github.com/kubevirt/containerized-data-importer/pull/3461

**Comment by awels** [comment] 2024-10-14 19:37
Okay, so I think I see what is going on, lets take the 1Gi example and follow the flow of the `calculateTargetSize()` function.
getAvailableSpaceBlockFunc returns the value from `blockdev --getsize64` which is `1073750016` So it then sets targetQuantity to that value. So far so good. Then we see dp.requestImageSize != "". It is in fact `1073741824` (1Gi). So then minQuantity comes out to 1Gi.

The reason we do this check is for 'shared' filesystem storage like hpp or nfs-csi, where the reported space is the entire disk, and we don't want to use it all. We want to use exactly what was requested, so we pick the minimum of the two. Aka we discovered the block devics > request size, so we picked the requested size as the 'available' space.

Now this value is stored as the available space for the virtual disk. Now in the validation routine, we run `qemu-img info <device>` which returns `1073750016` bytes as the virtual size. This is larger than the reported available size, and thus the validation fails.

So I think the most correct fix is to move code that makes the 'available' space the minimum inside the else that is associated with filesystem volumes. This way the targetSize returned is the value found from the call to blockdev.

**Comment by kvaps** [comment] 2024-10-14 22:27
Yeah my bad, sorry, I just reabased the PR

**Closed** 2024-10-16 18:44 UTC
Labels: kind/bug, lifecycle/rotten

**Comment by germanovm** [comment] 2024-12-20 05:54
Isn't there some other improvement that could be made here? For example, if I'm uploading a 5G ISO, it should fit just fine on any 10G PVC, regardless of a slightly bigger (or even smaller) PVC, like 10.001 or 9.999G.

The current logic seems to focus on the PVC size for the second step in the conversion and picks that discrepancy, whereas the actual ISO being uploaded can be much smaller and would fit anyway?

**Comment by akalenyu** [comment] 2024-12-22 08:44
> Isn't there some other improvement that could be made here? For example, if I'm uploading a 5G ISO, it should fit just fine on any 10G PVC, regardless of a slightly bigger (or even smaller) PVC, like 10.001 or 9.999G.
> 
> The current logic seems to focus on the PVC size for the second step in the conversion and picks that discrepancy, whereas the actual ISO being uploaded can be much smaller and would fit anyway?

Are you sure you're hitting the same issues/have the fix incorporated in your CDI version? following @kvaps' PR that check would not occur anymore for block volumes

**Comment by toschneck** [comment] 2025-04-08 22:08
Maybe the problem is not the sice, since some newer CDI version, blocks get mounted as other users, check https://github.com/kubevirt/containerized-data-importer/pull/2458
