### ISSUE TITLE
cdi importer: cannot set blockOwnerDeletion 

### ISSUE THREAD

**Issue by screeley44** [kubevirt/containerized-data-importer#290] opened 2018-07-31 17:28 UTC
This is fixed with PR 249 - will close once this is back-ported to v1.1.0

**Comment by jeffvance** [comment] 2018-07-31 17:32
May also be related to #287

**Comment by aglitke** [comment] 2018-07-31 17:41
Dupe of #287

**Closed by aglitke** 2018-07-31 17:41 UTC

**Comment by screeley44** [comment] 2018-07-31 18:35
it wasn't but issue 292 covers it as well :-)
