### ISSUE TITLE
cannot upload to DataVolume in WaitForFirstConsumer state, make sure the PVC is Bound

### ISSUE THREAD

**Issue by stanislaspiron** [kubevirt/containerized-data-importer#2645] opened 2023-03-16 17:08 UTC
**What happened**:
After upgrade CDI to version 1.56, I can't upload files to data volume anymore.
I deployed the same system multiple times with version 1.55.2 and 1.56.0
CDI version 1.56.0 never works, installed directly with this version or upgraded from 1.55.2
CDI version 1.55.2 always works.

To upload, I use the following command:
```
virtctl image-upload dv myimage --size=11Gi --image-path=myimage.qcow2 --uploadproxy-url https://$(kubectl get service -n cdi cdi-uploadproxy  -o jsonpath='{.spec.clusterIP}') --insecure --storage-class local-path --access-mode ReadWriteOnce
```

**What you expected to happen**:
keep upload working as in version 1.55.2

**How to reproduce it (as minimally and precisely as possible)**:
My system installation process is the following:

Installed system : Ubuntu 22.04 minimal server

- Install k3s
Do not install k3s version higher than 1.21. multus  does not support CNI 1.0.0 defined in pods created in k3s

```
curl -sfL https://get.k3s.io | sudo INSTALL_K3S_CHANNEL=v1.21 sh -s - --write-kubeconfig-mode 644
kubectl get node
```

- Install virtctl
```
cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
curl --output /tmp/virtctl -L https://github.com/kubevirt/kubevirt/releases/download/$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases/latest | awk -F '[",]' '/tag_name/{print $4}')/virtctl-$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases/latest | awk -F '[",]' '/tag_name/{print $4}')-linux-amd64
sudo install -o root -g root -m 0755 /tmp/virtctl /usr/local/bin/virtctl
```

- Install Containerized Data Importer 

This object is required to import ISO to PVC

```
curl -sL https://github.com/kubevirt/containerized-data-importer/releases/download/$(curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest | awk -F '[",]' '/tag_name/{print $4}')/cdi-operator.yaml | kubectl apply -f -
curl -sL https://github.com/kubevirt/containerized-data-importer/releases/download/$(curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest | awk -F '[",]' '/tag_name/{print $4}')/cdi-cr.yaml | kubectl apply -f -
```

**Additional context**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
    operator.cdi.kubevirt.io/createVersion: v1.55.2
    operator.cdi.kubevirt.io/updateVersion: v1.56.0
- Kubernetes version (use `kubectl version`): v1.21.14+k3s1
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS
- virtctl version: v0.59.0
- Kernel (e.g. `uname -a`): 5.15.0-67-generic
- Install tools: N/A
- Others: N/A

**Comment by alromeros** [comment] 2023-03-17 09:05
Hello @stanislaspiron, thanks for opening this issue.

Your case seems related to a recent change in CDI v1.56 that enables by default the `HonorWaitForFirstConsumer` feature gate (https://github.com/kubevirt/containerized-data-importer/pull/2445).

This feature gate changes the behavior of DataVolumes when using storage with `WaitForFirstConsumer` mode, so worker pods (import/clone/upload) are not scheduled until the PVC is bound. This change was introduced to be more consistent with `WaitForFirstConsumer` storage, and will be the expected behavior from now on.

If you still want to upload your DV, you can use the `--force-bind` flag when calling virtctl, so it binds the PVC ignoring the WFFC logic. You can also disable the HonorWaitForFirstConsumer feature gate if you want to permanently revert this behavior.

Hope this helps! You can check [our related documentation](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/waitforfirstconsumer-storage-handling.md) for more information.

**Comment by cheese** [comment] 2023-03-30 08:36
https://kubevirt.io/labs/kubernetes/lab2.html needs an update.

**Comment by alromeros** [comment] 2023-04-10 08:16
You are right, some sections in that lab are quite outdated (it says to create a PVC with import annotations instead of a DataVolume). @cheese did you notice any other outdated information? I'll discuss the topic with the team.

**Comment by alromeros** [comment] 2023-07-31 11:38
Forgot about this, will update the docs but that's a separate topic.
@stanislaspiron since the main topic of the issue has been addressed, are you ok with us closing the issue? Thanks!
/remove-lifecycle stale

**Comment by alromeros** [comment] 2023-08-02 15:26
@cheese opened a PR to update the lab https://github.com/kubevirt/kubevirt.github.io/pull/914. Closing this issue since the main topic has been addressed. Feel free to reopen if necessary, thanks!

**Closed by alromeros** 2023-08-02 15:26 UTC
Labels: kind/bug
