### ISSUE TITLE
CDI pvc/datavolume with empty url won't have error message in PVC/importer-pod

### ISSUE THREAD

**Issue by shiywang** [kubevirt/containerized-data-importer#418] opened 2018-09-04 09:36 UTC
Description of problem:

Version-Release number of selected component (if applicable):

How reproducible:

Create PVC with empty URL and importer-pod won't be created, But PVC is bound, so there's no error message for the user except cdi controller log

Steps to Reproduce:
1. oc create -f pvc.yml  (pvc with empty cdi.kubevirt.io/storage.import.endpoint: "" )

Actual results:
PVC bound successfully, no importer-pod created 

Expected results:
Could we put some error messages to PVC or importer-pod?

Now I have to check cdi-controller log message
E0904 09:33:21.644152       1 import-controller.go:206] error processing pvc "kubevirt-test-default/test-resrouce-whshfgthkm": annotation "cdi.kubevirt.io/storage.import.endpoint" in pvc "kubevirt-test-default/test-resrouce-whshfgthkm" is empty
 

Additional info:

**Comment by j-griffith** [comment] 2018-09-04 20:44
@shiywang could you share the pvc.yaml file you used?  I'd be interested in taking a look at reproducing this and see if I can fix it up.  Thanks!

**Comment by j-griffith** [comment] 2018-09-04 20:46
@shiywang Could you provide the pvc.yaml file you used?  I'd be happy to take a closer look at this.

**Comment by shiywang** [comment] 2018-09-05 12:08
> That seems to create the PVC but keep it in pending state "waiting for first consumer to be created before binding" which is what I'd expect. 

@j-griffith hi, that's the reason I filed an issue here. I also expected pvc could be pending or sth, but it bound successfully. the pvc file I use is 
```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: test-pvc
    annotations:
      cdi.kubevirt.io/storage.import.endpoint: ""
      cdi.kubevirt.io/storage.import.secretName: ""
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi
```

**Comment by awels** [comment] 2018-09-05 17:29
@j-griffith So I am guessing you are using local-volume PVs which stay in pending until a pod attaches it. @shiywang is probably using different storage, which will bind the PVC to a PV without being attached to a pod (maybe hostPath, or gluster based storage).

So from my perspective the controller is doing the right thing, it sees the endpoint is empty and thus there is no point in creating an importer pod, and it writes an error to the controller log indicating this. So with local volume storage the PVC will stay in pending (since no importer pod is created) and with other storage the PVC will stay bound just like if there is no endpoint annotation at all.

**Comment by awels** [comment] 2018-09-20 12:26
@aglitke Based on the above, should we close this?

**Closed** 2018-11-26 19:15 UTC
Labels: kind/bug
