### ISSUE TITLE
import failure in minishift with CDI 1.1

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/containerized-data-importer#294] opened 2018-07-31 18:53 UTC
Running latest 1.1 (includes RBAC stuff in #291) fails with this error:  

> E0731 18:23:11.267682       1 import-controller.go:206] error processing pvc "default/golden-pvc": importer pod API create errored: pods "importer-golden-pvc-cgtfc" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion apps/v1 Kind PersistentVolumeClaim: allowed by openshift authorizer, no matches for apps/, Kind=PersistentVolumeClaim

This is because PersistentVolumeClaim is in v1 namespace not apps/v1.

PR forthcoming

**Comment by aglitke** [comment] 2018-07-31 18:57
Dupe of #292 fixed by #293

**Closed** 2018-07-31 18:59 UTC
